<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Session;

// Moneris
use CraigPaul\Moneris\Moneris;

use Illuminate\Support\Facades\Hash;

use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Auth;

use Illuminate\Support\Facades\Mail;

use Illuminate\Support\Facades\Validator;

use Illuminate\Support\Facades\Log;

use App\User as User;

use App\Mail\sendEmail;

use App\CreateEvent as CreateEvent;

use App\SetupBilling as SetupBilling;

use App\InvoicePayment as InvoicePayment;

use App\ImportExcel as ImportExcel;

use App\ClientInfo as ClientInfo;

use App\OrganizationPay as OrganizationPay;

use App\PaycaWithdraw as PaycaWithdraw;

use App\Epaywithdraw as Epaywithdraw;

use App\Statement as Statement;

use App\ReceivePay as ReceivePay;

use App\AddCard as AddCard;

use App\AddBank as AddBank;

use App\BankWithdrawal as BankWithdrawal;


use App\CcWithdrawal as CcWithdrawal;

use App\Classes\mpgGlobals;
use App\Classes\httpsPost;
use App\Classes\mpgHttpsPost;
use App\Classes\mpgHttpsPostStatus;
use App\Classes\mpgResponse;
use App\Classes\mpgRequest;
use App\Classes\mpgCustInfo;
use App\Classes\mpgRecur;
use App\Classes\mpgAvsInfo;
use App\Classes\mpgCvdInfo;
use App\Classes\mpgAchInfo;
use App\Classes\mpgConvFeeInfo;
use App\Classes\mpgTransaction;
use App\Classes\MpiHttpsPost;
use App\Classes\MpiResponse;
use App\Classes\MpiRequest;
use App\Classes\MpiTransaction;
use App\Classes\riskHttpsPost;
use App\Classes\riskResponse;
use App\Classes\riskRequest;
use App\Classes\mpgSessionAccountInfo;
use App\Classes\mpgAttributeAccountInfo;
use App\Classes\riskTransaction;
use App\Classes\mpgAxLevel23;
use App\Classes\axN1Loop;
use App\Classes\axRef;
use App\Classes\axIt1Loop;
use App\Classes\axIt106s;
use App\Classes\axTxi;
use App\Classes\mpgAxRaLevel23;
use App\Classes\mpgVsLevel23;
use App\Classes\vsPurcha;
use App\Classes\vsPurchl;
use App\Classes\vsCorpai;
use App\Classes\vsCorpas;
use App\Classes\vsTripLegInfo;
use App\Classes\mpgMcLevel23;
use App\Classes\mcCorpac;
use App\Classes\mcCorpai;
use App\Classes\mcCorpas;
use App\Classes\mcCorpal;
use App\Classes\mcCorpar;
use App\Classes\mcTax;
use App\Classes\CofInfo;
use App\Classes\MCPRate;


class MonerisController extends Controller
{

    public $to;
    public $name;
    public $email;
    public $transaction_date;
    public $invoice_no;
    public $payee_ref_no;
    public $transaction_ref;
    public $description;
    public $payment_due_date;
    public $amount;
    public $address;
    public $clientname;
    public $subject;
    public $subject2;
    public $paypurpose;
    public $service;
    public $city;
    public $state;
    public $zipcode;
    public $coy_name;
    public $url = "https://exbc.ca/api/v1/points/earnpoint";
    // public $url = "http://localhost:4000/api/v1/points/earnpoint";
    public $curl_data;

	public function __construct(Request $request){

		
	}


public function purchase(Request $req){

		/**************************** Request Variables *******************************/

/************************* Transactional Variables ****************************/

// Test API
// $store_id='monca04155';
// $api_token='KvTMr066FKlJm9rD3i71';

// Live API
// $store_id='gwca026583';
// $api_token='sssLFi2U8VFO0oWvPWax';
$store_id='gwca045238';
$api_token='V9XOY4JBS4JII01xBFch';

// $type='purchase';
// $cust_id='cust id';
// $order_id='ord-'.date("dmy-Gis");
// $amount='1.00';
// $pan='4242424242424242';
// $expiry_date='2011';
// $crypt='7';
// $dynamic_descriptor='123';
// $status_check = 'false';

if($req->typepayamount != 0){
	$amount = $req->typepayamount;

}
else{
	$amount = $req->amount;
}


$month = $req->month;

$type='purchase';
$cust_id= $req->invoice_no;
$order_id='ord-'.date("dmy-Gis");
$amount= number_format($amount, 2);

$pan= $req->creditcard_no;
$expiry_date= $req->expirydate.$month;
$crypt='7';
$dynamic_descriptor= 'Invoice Payment for PaySprint platform of EXBC';
$status_check = 'false';


/*********************** Transactional Associative Array **********************/
$txnArray=array('type'=>$type,
     		    'order_id'=>$order_id,
     		    'cust_id'=>$cust_id,
    		    'amount'=>$amount,
   			    'pan'=>$pan,
   			    'expdate'=>$expiry_date,
   			    'crypt_type'=>$crypt,
   			    'dynamic_descriptor'=>$dynamic_descriptor
				//,'wallet_indicator' => '' //Refer to documentation for details
				//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
   		       );
/**************************** Transaction Object *****************************/



$mpgTxn = new mpgTransaction($txnArray);


/******************* Credential on File **********************************/
$cof = new CofInfo();
$cof->setPaymentIndicator("Z");
$cof->setPaymentInformation("2");
$cof->setIssuerId("168451306048014");
$mpgTxn->setCofInfo($cof);

/****************************** Request Object *******************************/
$mpgRequest = new mpgRequest($mpgTxn);
$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
$mpgRequest->setTestMode(false); //false or comment out this line for production transactions
/***************************** HTTPS Post Object *****************************/
/* Status Check Example
$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);
*/
$mpgHttpPost = new mpgHttpsPost($store_id,$api_token,$mpgRequest);
/******************************* Response ************************************/
$mpgResponse=$mpgHttpPost->getMpgResponse();

// dd($mpgResponse);


if($mpgResponse->responseData['Message'] == "APPROVED           *                    ="){

		// Insert Record to DB...
		$insPay = InvoicePayment::updateOrCreate(['invoice_no' => $req->invoice_no],['transactionid' => $mpgResponse->responseData['ReceiptId'], 'name' => $req->name, 'email' => $req->email, 'amount' => $mpgResponse->responseData['TransAmount'], 'invoice_no' => $req->invoice_no, 'service'=> $req->service, 'client_id' => $req->user_id, 'payment_method' => $req->payment_method]);


		if($insPay){
			// Update Import Excel Record
			$getInv = ImportExcel::where('invoice_no', $req->invoice_no)->get();

			if(count($getInv) > 0){
				// Get Amount
				$prevAmount = $getInv[0]->amount;

				$paidAmount = $req->amount;

				$newAmount = $prevAmount - $paidAmount;

                $instcount = $getInv[0]->installcount + 1;

                if($getInv[0]->installlimit > $instcount){
                    $installcounter = $getInv[0]->installlimit;
                }
                else{
                    $installcounter = $instcount;
                }

                ImportExcel::where('invoice_no', $req->invoice_no)->update(['installcount' => $installcounter, 'payment_status' => 1]);

				// Update Price Record
				$updtPrice = InvoicePayment::where('transactionid', $mpgResponse->responseData['ReceiptId'])->update(['remaining_balance' => $newAmount, 'opening_balance' => $prevAmount, 'payment_method' => $req->payment_method]);

				if($updtPrice == 1){

                    $client = ClientInfo::where('user_id', $req->user_id)->first();

                    // Insert PAYCAWithdraw
                    PaycaWithdraw::insert(['withdraw_id' => $mpgResponse->responseData['ReceiptId'], 'client_id' => $req->user_id, 'client_name' => $req->name, 'card_method' => $req->payment_method, 'client_email' => $req->email, 'amount_to_withdraw' => $mpgResponse->responseData['TransAmount'], 'remittance' => 0]);


                    // Insert Statement
                        $activity = "Payment for ".$req->service." to ".$client->business_name;
                        $credit = 0;
                        $debit = $req->amount;
                        $balance = $newAmount;
                        $status = "Paid";
                        $action = "Payment";
                        $regards = $req->user_id;
                        $reference_code = $mpgResponse->responseData['ReceiptId'];
                        $trans_date = date('Y-m-d');
                        $statement_route = "invoice";
                        
                        $this->insStatement($req->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 0, $statement_route);



                        
                            $thisuser = User::where('email', $req->email)->first();


                    $resData = ['res' => 'Payment Successful', 'message' => 'success', 'title' => 'Good!'];
                    
                    $response = 'Payment Successful';
                    $action = 'success';

                    $this->createNotification($thisuser->ref_code, "Payment successfully made for ".$req->service." to ".$client->business_name);
				}
				else{
                    $resData = ['res' => 'Something went wrong', 'message' => 'info', 'title' => 'Oops!'];
                    
                    $response = 'Something went wrong';
                    $action = 'error';

				}

			}
			else{
                $resData = ['res' => 'Invoice not found', 'message' => 'error', 'title' => 'Oops!'];
                
                $response = 'Invoice not found';
            $action = 'error';

			}

		}
		else{
            $resData = ['res' => 'Information not documented, contact Admin', 'message' => 'info', 'title' => 'Oops!'];
            
            $response = 'Information not documented, contact Admin';
            $action = 'error';

        }
        
        
}
else{
    $resData = ['res' => $mpgResponse->responseData['Message'], 'message' => 'error', 'title' => 'Oops!'];
    
    $response = $mpgResponse->responseData['Message'];
    $action = 'error';
}

    // return $this->returnJSON($resData, 200);

    return redirect()->route('invoice')->with($action, $response);

}


    // Pay Invoice from Wallet
    public function payInvoice(Request $req){

        // dd($req->all());

        $validator = Validator::make($req->all(), [
                     'invoice_no' => 'required|string',
                     'amount' => 'required|string',
                     'merchant_id' => 'required|string',
                     'service' => 'required|string',
                     'payment_method' => 'required|string',
                     'currencyCode' => 'required|string',
                     'amountinvoiced' => 'required|string',
                     'payInstallment' => 'required|string',
                ]);

            if($validator->passes()){

                try {
                        $transactionID = "invoice-".date('dmY').time();

                            $thisuser = User::where('api_token', $req->bearerToken())->first();

                            // Get My Wallet Balance
                            $walletBalance = $thisuser->wallet_balance - $req->amount;

                            User::where('api_token', $req->bearerToken())->update(['wallet_balance' => $walletBalance]);

                            // Update Merchant Wallet 

                            $thismerchant = User::where('ref_code', $req->merchant_id)->first();

                            // Update Merchant Wallet Balance
                            $merchantwalletBalance = $thismerchant->wallet_balance + $req->amount;

                            User::where('ref_code', $req->merchant_id)->update(['wallet_balance' => $merchantwalletBalance]);

                            // Get Invoice Service

                            // $invData = ImportExcel::where('invoice_no', $req->invoice_no)->first();

                            $purpose = $req->service;


                            $insPay = InvoicePayment::updateOrCreate(['invoice_no' => $req->invoice_no],['transactionid' => $transactionID, 'name' => $thisuser->name, 'email' => $thisuser->email, 'amount' => $req->amount, 'invoice_no' => $req->invoice_no, 'service'=> $purpose, 'client_id' => $req->merchant_id, 'payment_method' => $req->payment_method]);


                    if($insPay){
                        // Update Import Excel Record
                        $getInv = ImportExcel::where('invoice_no', $req->invoice_no)->get();

                        if(count($getInv) > 0){


                            if($req->payInstallment == "Yes"){

                                if($getInv[0]->total_amount != null){
                                    // Get Amount
                                    $prevAmount = $getInv[0]->total_amount;
                                }
                                else{
                                    $prevAmount = $getInv[0]->amount;
                                }

                                $paidAmount = $req->amount;

                                $newAmount = $prevAmount - $paidAmount;

                                $instcount = $getInv[0]->installcount + 1;

                                if($getInv[0]->installlimit > $instcount){
                                    $installcounter = $getInv[0]->installlimit;
                                }
                                else{
                                    $installcounter = $instcount;
                                }

                                $payment_status = 2;

                            }
                            else{

                                if($getInv[0]->total_amount != 0){
                                    // Get Amount
                                    $prevAmount = $getInv[0]->total_amount;
                                }
                                else{
                                    $prevAmount = $getInv[0]->amount;
                                }

                                $paidAmount = $req->amount;

                                $newAmount = $prevAmount - $paidAmount;

                                $instcount = $getInv[0]->installcount;

                                if($getInv[0]->installlimit > $instcount){
                                    $installcounter = $getInv[0]->installlimit;
                                }
                                else{
                                    $installcounter = $instcount;
                                }

                                $payment_status = 1;
                            }


                            // if payment status is 2, there sre still some pending payments to make, if 1, payments are cleared off


                            ImportExcel::where('invoice_no', $req->invoice_no)->update(['installcount' => $installcounter, 'payment_status' => $payment_status, 'remaining_balance' => $newAmount]);

                            // Update Price Record
                            $updtPrice = InvoicePayment::where('transactionid', $transactionID)->update(['remaining_balance' => $newAmount, 'opening_balance' => $prevAmount, 'payment_method' => $req->payment_method]);

                            if(isset($updtPrice)){

                                $client = ClientInfo::where('user_id', $req->merchant_id)->get();

                                // Insert PAYCAWithdraw
                                PaycaWithdraw::insert(['withdraw_id' => $transactionID, 'client_id' => $req->merchant_id, 'client_name' => $req->name, 'card_method' => $req->payment_method, 'client_email' => $req->email, 'amount_to_withdraw' => $req->amount, 'remittance' => 0]);


                                    $activity = "Payment for ".$purpose." from ".$req->payment_method;
                                    $credit = 0;
                                    $debit = number_format($req->amount, 2);
                                    $balance = $newAmount;
                                    $status = "Delivered";
                                    $action = "Wallet debit";
                                    $regards = $req->merchant_id;
                                    $reference_code = $transactionID;
                                    $trans_date = date('Y-m-d');
                                    $statement_route = "wallet";


                                    // My Statement
                                    $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 0, $statement_route); 

                                    $this->name = $thisuser->name;
                                    $this->email = $thisuser->email;
                                    // $this->email = "bambo@vimfile.com";
                                    $this->subject = "Your Invoice # [".$req->invoice_no."] of ".$req->currencyCode.' '.number_format($req->amount, 2).' from '.$thismerchant->businessname.' '.number_format($req->amount, 2)." is Paid";

                                    $this->message = '<p>Hi '.$thisuser->name.' You have successfully paid invoice of <strong>'.$req->currencyCode.' '.number_format($req->amount, 2).'</strong> to '.$thismerchant->name.' for '.$purpose.'. Your remaining balance is to pay <strong>'.$req->currencyCode.' '.number_format($newAmount, 2).'</strong>. You now have <strong>'.$req->currencyCode.' '.number_format($walletBalance, 2).'</strong> balance in PaySprint Wallet account</p>';

                                    $this->sendEmail($this->email, "Fund remittance");

                                    $sendMsg = 'Hi '.$thisuser->name.' You have successfully paid invoice of '.$req->currencyCode.' '.number_format($req->amount, 2).' to '.$thismerchant->name.' for '.$purpose.'. Your remaining balance is to pay '.$req->currencyCode.' '.number_format($newAmount, 2).'. You now have '.$req->currencyCode.' '.number_format($walletBalance, 2).' balance in PaySprint Wallet account';
                                    $sendPhone = "+".$thisuser->code.$thisuser->telephone;

                                    $this->sendMessage($sendMsg, $sendPhone);

                                    
                                    /*---------------------------------------------------------------------------------------------------------------------*/ 

                                    // Merchant Statement

                                    $activity = "Added ".$req->currencyCode.''.number_format($req->amount, 2)." to Wallet";
                                    $credit = number_format($req->amount, 2);
                                    $debit = 0;
                                    $reference_code = $transactionID;
                                    $balance = 0;
                                    $trans_date = date('Y-m-d');
                                    $status = "Delivered";
                                    $action = "Wallet credit";
                                    $regards = $thismerchant->ref_code;
                                    $statement_route = "wallet";

                                    // Senders statement
                                    $this->insStatement($thismerchant->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);


                                    $this->name = $thismerchant->name;
                                    $this->email = $thismerchant->email;
                                    // $this->email = "bambo@vimfile.com";
                                    $this->subject = $thisuser->name." has paid Invoice: [".$req->invoice_no."]";

                                    $this->message = '<p>You have received <strong>'.$req->currencyCode.''.number_format($req->amount, 2).'</strong> for <b>INVOICE: '.$req->invoice_no.'</b> made by <b>'.$thisuser->name.'</b>, remaining balance to pay is '.$req->currencyCode.' '.number_format($newAmount, 2).'.</p> <p>You now have <strong>'.$req->currencyCode.''.number_format($merchantwalletBalance, 2).'</strong> balance in your wallet account with PaySprint</p>';

                                    $this->sendEmail($this->email, "Fund remittance");

                                    $recMesg = 'You have received '.$req->currencyCode.' '.number_format($req->amount, 2).' for INVOICE: '.$req->invoice_no.' made by '.$thisuser->name.', remaining balance to pay is '.$req->currencyCode.' '.number_format($newAmount, 2).'. You now have '.$req->currencyCode.' '.number_format($merchantwalletBalance, 2).' balance in your wallet account with PaySprint';
                                    $recPhone = "+".$thismerchant->code.$thismerchant->telephone;

                                    $this->sendMessage($recMesg, $recPhone);


                                    $userInfo = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();


                                $data = $userInfo;
                                $status = 200;
                                $message = 'You have successfully paid invoice of '.$req->currencyCode.' '.number_format($req->amount, 2);

                                $this->createNotification($thisuser->ref_code, $sendMsg);
                                $this->createNotification($thismerchant->ref_code, $recMesg);
                            }
                            else{
                                
                                $response = 'Something went wrong';

                                $data = [];
                                $status = 400;
                                $message = $response;

                            }

                        }
                        else{
                            
                            $response = 'Invoice not found';
                            $data = [];
                            $status = 400;
                            $message = $response;

                        }

                    }
                    else{
                        $response = 'Information not documented, contact Admin';

                        $data = [];
                        $status = 400;
                        $message = $response;

                    }
                } catch (\Throwable $th) {
                    $data = [];
                    $status = 400;
                    $message = "Error: ".$th;
                }


            }
            else{

                $error = implode(",",$validator->messages()->all());

                $data = [];
                $status = 400;
                $message = $error;
            }


        $resData = ['data' => $data, 'message' => $message, 'status' => $status];

        return $this->returnJSON($resData, $status);

    }




    // Add Money to Wallet
    public function addMoneyToWallet(Request $req){

        // dd($req->all());

        $validator = Validator::make($req->all(), [
                    //  'card_id' => 'required|string',
                     'amount' => 'required|string',
                     'currencyCode' => 'required|string',
                     'conversionamount' => 'required|string',
                ]);

            if($validator->passes()){

                $thisuser = User::where('api_token', $req->bearerToken())->first();

                $monerisDeductamount = $req->conversionamount;
                // $monerisDeductamount = $this->currencyConvert($req->currencyCode, $req->amount);

                if($req->paymentToken != null){

                        $reference_code = $req->paymentToken;
                        
                        // Update Wallet Balance
                        $walletBal = $thisuser->wallet_balance + $req->amounttosend;
                        User::where('api_token', $req->bearerToken())->update(['wallet_balance' => $walletBal]);

                        $userData = User::select('id', 'ref_code as refCode', 'name', 'email', 'telephone', 'wallet_balance as walletBalance', 'number_of_withdrawals as noOfWithdrawals')->where('api_token', $req->bearerToken())->first();

                        $activity = "Added ".$req->currencyCode.''.number_format($req->amounttosend, 2)." to Wallet including a fee charge of ".$req->currencyCode.''.number_format($req->commissiondeduct, 2)." was deducted from your GooglePay Credit/Debit Card";
                        $credit = $req->amounttosend;
                        $debit = 0;
                        $reference_code = $req->paymentToken;
                        $balance = 0;
                        $trans_date = date('Y-m-d');
                        $status = "Delivered";
                        $action = "Wallet credit";
                        $regards = $thisuser->ref_code;
                        $statement_route = "wallet";

                        // Senders statement
                        $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                        $this->getfeeTransaction($reference_code, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);

                        // Notification


                            $this->name = $thisuser->name;
                            $this->email = $thisuser->email;
                            $this->subject = $req->currencyCode.' '.number_format($req->amounttosend, 2)." now added to your wallet with PaySprint";

                            $this->message = '<p>You have added <strong>'.$req->currencyCode.' '.number_format($req->amounttosend, 2).'</strong> to your wallet with PaySprint. You now have <strong>'.$req->currencyCode.' '.number_format($walletBal, 2).'</strong> balance in your account</p>';

                            $sendMsg = 'You have added '.$req->currencyCode.' '.number_format($req->amounttosend, 2).' to your wallet with PaySprint. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                            $sendPhone = "+".$thisuser->code.$thisuser->telephone;


                            $this->sendMessage($sendMsg, $sendPhone);

                            $this->sendEmail($this->email, "Fund remittance");

                            $userInfo = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();

                        $data = $userInfo;
                        $status = 200;
                        $message = 'You have successfully added '.$req->currencyCode.' '.number_format($req->amounttosend, 2).' to your wallet';

                        $this->createNotification($thisuser->ref_code, $sendMsg);


                }
                else{


                $response = $this->monerisWalletProcess($req->bearerToken(), $req->card_id, $monerisDeductamount, "purchase", "PaySprint Add Money to the Wallet of ".$thisuser->name, $req->mode);


                    if($response->responseData['Message'] == "APPROVED           *                    ="){

                        $reference_code = $response->responseData['ReceiptId'];

                        $cardDetails = AddCard::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();

                        $cardNo = str_repeat("*", strlen($cardDetails->card_number)-4) . substr($cardDetails->card_number, -4);
                        
                        // Update Wallet Balance
                        $walletBal = $thisuser->wallet_balance + $req->amounttosend;
                        User::where('api_token', $req->bearerToken())->update(['wallet_balance' => $walletBal]);

                        $userData = User::select('id', 'ref_code as refCode', 'name', 'email', 'telephone', 'wallet_balance as walletBalance', 'number_of_withdrawals as noOfWithdrawals')->where('api_token', $req->bearerToken())->first();

                        $activity = "Added ".$req->currencyCode.''.number_format($req->amounttosend, 2)." to Wallet including fee charge of ".$req->currencyCode.''.number_format($req->commissiondeduct, 2)." was deducted from Card: ".wordwrap($cardNo, 4, '-', true);
                        $credit = $req->amounttosend;
                        $debit = 0;
                        $reference_code = $response->responseData['ReceiptId'];
                        $balance = 0;
                        $trans_date = date('Y-m-d');
                        $status = "Delivered";
                        $action = "Wallet credit";
                        $regards = $thisuser->ref_code;
                        $statement_route = "wallet";

                        // Senders statement
                        $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                        $this->getfeeTransaction($reference_code, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);

                        // Notification


                            $this->name = $thisuser->name;
                            $this->email = $thisuser->email;
                            $this->subject = $req->currencyCode.' '.number_format($req->amounttosend, 2)." now added to your wallet with PaySprint";

                            $this->message = '<p>You have added <strong>'.$req->currencyCode.' '.number_format($req->amounttosend, 2).'</strong> to your wallet with PaySprint. You now have <strong>'.$req->currencyCode.' '.number_format($walletBal, 2).'</strong> balance in your account</p>';

                            $sendMsg = 'You have added '.$req->currencyCode.' '.number_format($req->amounttosend, 2).' to your wallet with PaySprint. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                            $sendPhone = "+".$thisuser->code.$thisuser->telephone;


                            $this->sendMessage($sendMsg, $sendPhone);

                            $this->sendEmail($this->email, "Fund remittance");

                            $userInfo = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();

                        $data = $userInfo;
                        $status = 200;
                        $message = 'You have successfully added '.$req->currencyCode.' '.number_format($req->amounttosend, 2).' to your wallet';

                        $this->createNotification($thisuser->ref_code, $sendMsg);
                        

                    }
                    else{
                        $data = [];
                        $message = $response->responseData['Message'];
                        $status = 400;
                    }
                }

                



                

            }
            else{

                $error = implode(",",$validator->messages()->all());

                $data = [];
                $status = 400;
                $message = $error;
            }


        $resData = ['data' => $data, 'message' => $message, 'status' => $status];

        return $this->returnJSON($resData, $status);

    }



    public function moneyWithdrawal(Request $req){

        // dd($req->all());

        $validator = Validator::make($req->all(), [
                    //  'card_id' => 'required|string',
                     'amount' => 'required|string',
                     'transaction_pin' => 'required|string',
                     'currencyCode' => 'required|string',
                     'conversionamount' => 'required|string',
                     'card_type' => 'required|string',
                ]);

                if($validator->passes()){

                    $thisuser = User::where('api_token', $req->bearerToken())->first();

                    // Check amount in wallet
                    if($req->amount > $thisuser->wallet_balance){
                        // Insufficient amount for withdrawal

                        $data = [];
                        $message = "Insufficient amount to withdraw";
                        $status = 400;
                    }
                    else{

                            // Do convert amount to dollars

                            // This 1.35 is commission charge, kindly calculate again

                                // $monerisDeductamount = $req->conversionamount - 1.35;
                                $monerisDeductamount = $req->conversionamount;

                                // Get Transaction record for last money added to wallet
                                $getTrans = Statement::where('reference_code', 'LIKE', '%ord-%')->where('reference_code', 'LIKE', '%wallet-%')->where('user_id', $thisuser->email)->latest()->first();


                                // Check Transaction PIn
                                if($thisuser->transaction_pin != null){
                                    // Validate Transaction PIN
                                    if(Hash::check($req->transaction_pin, $thisuser->transaction_pin)){


                                        /*
                                            1. Check card detail
                                            2. If EXBC Prepaid Card, take to EXBC Endpoint to withdraw
                                            3. Return Response and Debit wallet
                                        */  

                                        // Get Card Details
                                        $cardDetails = AddCard::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();

                                        if(isset($cardDetails) == true && $cardDetails->card_provider == "EXBC Prepaid Card"){

                                            $transaction_id = "wallet-".date('dmY').time();
                                            $reference_code = "PS_".$thisuser->ref_code;

                                            if(env('APP_ENV') == "local"){
                                                $url = "http://localhost:4000/api/v1/paysprint/loadcard";
                                            }
                                            else{
                                                $url = "https://exbc.ca/api/v1/paysprint/loadcard";
                                            }

                                            $mydata = array(
                                                'transaction_id' => $transaction_id, 
                                                'reference_code' => $reference_code, 
                                                'email' => $thisuser->email, 
                                                'amount' => $req->amounttosend, 
                                                'card_number' => $cardDetails->card_number,
                                                'name' => $thisuser->name,
                                            );

                                            $token = "base64:HgMO6FDHGziGl01OuLH9mh7CeP095shB6uuDUUClhks=";


                                           $response = $this->curlPost($url, $mydata, $token);

                                           if($response->status == 200){
                                                $resData = $this->debitWalletForCard($thisuser->ref_code, $req->amount, $cardDetails->card_provider, $transaction_id);

                                                $status = $resData['status'];
                                                // $data = $resData['data'];
                                                $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                                $message = $response->message;
                                                
                                            }
                                            else{
                                                $status = $response->status;
                                                // $data = $response->data;
                                                $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();;
                                                $message = $response->message;
                                                $resData = ['data' => $data, 'message' => $message, 'status' => $status];
                                            }

                                            $activity = "Withdraw ".$req->currencyCode.''.$req->amount." from Wallet to EXBC Prepaid Card";
                                            $credit = 0;
                                            $debit = $req->amount;
                                            $reference_code = $transaction_id;
                                            $balance = 0;
                                            $trans_date = date('Y-m-d');
                                            $status = "Delivered";
                                            $action = "Wallet debit";
                                            $regards = $thisuser->ref_code;
                                            $statement_route = "wallet";

                                            $walletBal = $thisuser->wallet_balance - $req->amount;
                                                $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                User::where('api_token', $req->bearerToken())->update([
                                                    'wallet_balance' => $walletBal,
                                                    'number_of_withdrawals' => $no_of_withdraw
                                                ]);

                                            // Senders statement
                                            $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                                            $this->createNotification($thisuser->ref_code, "Hello ".strtoupper($thisuser->name).", ".$message);

                                            $this->getfeeTransaction($transaction_id, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);

                                        }

                                        elseif($req->card_type == "Bank Account"){

                                            $bankDetails = AddBank::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();   

                                            Log::info("Card ID: ".$req->card_id." Type: ".$req->card_type); 

                                            if(isset($bankDetails)){

                                                $transaction_id = "wallet-".date('dmY').time();
                                            // Save Payment for Admin
                                            $insRec = BankWithdrawal::updateOrInsert(['transaction_id' => $transaction_id], ['transaction_id' => $transaction_id, 'ref_code' => $thisuser->ref_code, 'bank_id' => $req->card_id, 'amountToSend' => $req->amounttosend]);


                                            $mydata = BankWithdrawal::where('transaction_id', $transaction_id)->first();


                                            $status = 200;
                                            $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                            $message = "Your wallet withdrawal to Bank Account ".$bankDetails->accountNumber." - ".$bankDetails->bankName." has been received. This will take 10 working days to process payment. Thanks";


                                            $walletBal = $thisuser->wallet_balance - $req->amount;
                                                $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                User::where('api_token', $req->bearerToken())->update([
                                                    'wallet_balance' => $walletBal,
                                                    'number_of_withdrawals' => $no_of_withdraw
                                                ]);


                                            $activity = "Withdraw ".$req->currencyCode.''.number_format($req->amount, 2)." from Wallet to Bank Account ".$bankDetails->bankName." - ".$bankDetails->accountNumber;
                                            $credit = 0;
                                            $debit = number_format($req->amount, 2);
                                            $reference_code = $transaction_id;
                                            $balance = 0;
                                            $trans_date = date('Y-m-d');
                                            $thistatus = "Delivered";
                                            $action = "Wallet debit";
                                            $regards = $thisuser->ref_code;
                                            $statement_route = "wallet";

                                            // Senders statement
                                            $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $thistatus, $action, $regards, 1, $statement_route);


                                            $sendMsg = 'Hello '.strtoupper($thisuser->name).', The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your Bank Account '.$bankDetails->bankName.' and Account Number: '.$bankDetails->accountNumber.' has been received and will take up to 10 working days to process payment. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                                                $sendPhone = "+".$thisuser->code.$thisuser->telephone;

                                            $this->createNotification($thisuser->ref_code, $sendMsg);

                                            $this->getfeeTransaction($transaction_id, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);

                                            }
                                            else{
                                                $data = [];
                                                $message = "No bank record found for your account";
                                                $status = 400;
                                            }
                                            
                                            


                                            $resData = ['data' => $data, 'message' => $message, 'status' => $status];


                                        }
                                        else{   

                                            if(isset($getTrans) == true){
                                                $transaction_id = $getTrans->reference_code;
                                            }
                                            else{
                                                $transaction_id = "wallet-".date('dmY').time();
                                            }

                                            $customer_id = $thisuser->ref_code;

                                            // Get Card Detail
                                            $card_number = $cardDetails->card_number;
                                            $month = $cardDetails->month;
                                            $year = $cardDetails->year;


                                            $this->creditCardWithdrawalRequest($thisuser->ref_code, $transaction_id, $customer_id, $card_number, $month, $year, $req->amount);



                                                // Proceed to Withdrawal

                                                // $response = $this->monerisWalletProcess($req->bearerToken(), $req->card_id, $monerisDeductamount, "ind_refund", "PaySprint Withdraw from Wallet to ".$thisuser->name, $req->mode);

                                                // if($response->responseData['Message'] == "APPROVED           *                    ="){

                                                        $walletBal = $thisuser->wallet_balance - $req->amount;
                                                        $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                        User::where('api_token', $req->bearerToken())->update([
                                                            'wallet_balance' => $walletBal,
                                                            'number_of_withdrawals' => $no_of_withdraw
                                                        ]);

                                                        // Update Statement

                                                        $userData = User::select('id', 'ref_code as refCode', 'name', 'email', 'telephone', 'wallet_balance as walletBalance', 'number_of_withdrawals as noOfWithdrawals')->where('api_token', $req->bearerToken())->first();

                                                        $activity = "Withdraw ".$req->currencyCode.''.number_format($req->amount, 2)." from Wallet to Credit/Debit card";
                                                        $credit = 0;
                                                        $debit = number_format($req->amount, 2);
                                                        // $reference_code = $response->responseData['ReceiptId'];
                                                        $reference_code = $transaction_id;
                                                        $balance = 0;
                                                        $trans_date = date('Y-m-d');
                                                        $status = "Delivered";
                                                        $action = "Wallet debit";
                                                        $regards = $thisuser->ref_code;
                                                        $statement_route = "wallet";

                                                        // Senders statement
                                                        $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                                                        // Notification
                                                        $cardDetails = AddCard::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();

                                                        $cardNo = str_repeat("*", strlen($cardDetails->card_number)-4) . substr($cardDetails->card_number, -4);


                                                        $this->name = $thisuser->name;
                                                        $this->email = $thisuser->email;
                                                        $this->subject = $req->currencyCode.' '.number_format($req->amount, 2)." has been Withdrawn from your Wallet with PaySprint";

                                                        $this->message = '<p>The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your Card Name: <strong>'.$cardDetails->card_name.'</strong> and Number: <strong>'.wordwrap($cardNo, 4, '-', true).'</strong> is successful. This will take about 10 working days before it reflect in your bank account or credit card. </p><p>You now have <strong>'.$req->currencyCode.' '.number_format($walletBal, 2).'</strong> balance in your account</p>';


                                                        

                                                        $sendMsg = 'The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your '.$cardDetails->card_name.' and Number: '.wordwrap($cardNo, 4, '-', true).' is successful. This will take about 10 working days before it reflect in your bank account or credit card. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                                                        $sendPhone = "+".$thisuser->code.$thisuser->telephone;

                                                        $this->createNotification($thisuser->ref_code, $sendMsg);

                                                        $this->getfeeTransaction($reference_code, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);


                                                        $this->sendMessage($sendMsg, $sendPhone);

                                                        $this->sendEmail($this->email, "Fund remittance");

                                                        $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                                        $status = 200;
                                                        // $message = $req->currencyCode.' '.number_format($req->amount, 2).' is debited from your Wallet';
                                                        $message = $sendMsg;

                                                        

                                                // }
                                                // else{
                                                //     $data = [];
                                                //         $message = $response->responseData['Message'];
                                                //         $status = 400;
                                                // }
                                        }



                                        

                                    }
                                    else{
                                        $data = [];
                                        $message = "Invalid transaction pin";
                                        $status = 400;
                                    }

                                }
                                else{
                                    // Set new transaction pin and validate

                                    if(Hash::check($req->password, $thisuser->password)){

                                        if($req->transaction_pin != $req->confirm_transaction_pin){

                                            $data = [];
                                            $message = "Transaction pin does not match";
                                            $status = 400;

                                        }else{

                                            // Update Transaction pin
                                            User::where('api_token', $req->bearerToken())->update(['transaction_pin' => Hash::make($req->transaction_pin)]);


                                            /*
                                            1. Check card detail
                                            2. If EXBC Prepaid Card, take to EXBC Endpoint to withdraw
                                            3. Return Response and Debit wallet
                                        */  

                                        // Get Card Details
                                        $cardDetails = AddCard::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();

                                        if(isset($cardDetails) == true && $cardDetails->card_provider == "EXBC Prepaid Card"){

                                            $transaction_id = "wallet-".date('dmY').time();
                                            $reference_code = "PS_".$thisuser->ref_code;

                                            if(env('APP_ENV') == "local"){
                                                $url = "http://localhost:4000/api/v1/paysprint/loadcard";
                                            }
                                            else{
                                                $url = "https://exbc.ca/api/v1/paysprint/loadcard";
                                            }

                                            $mydata = array(
                                                'transaction_id' => $transaction_id, 
                                                'reference_code' => $reference_code, 
                                                'email' => $thisuser->email, 
                                                'amount' => $req->amounttosend, 
                                                'card_number' => $cardDetails->card_number,
                                                'name' => $thisuser->name,
                                            );

                                            $token = "base64:HgMO6FDHGziGl01OuLH9mh7CeP095shB6uuDUUClhks=";


                                           $response = $this->curlPost($url, $mydata, $token);

                                            if($response->status == 200){
                                                $resData = $this->debitWalletForCard($thisuser->ref_code, $req->amount, $cardDetails->card_provider, $transaction_id);
                                                
                                                $status = $resData['status'];
                                                $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                                $message = $response->message;
                                                
                                            }
                                            else{
                                                $status = $response->status;
                                                $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                                $message = $response->message;
                                                $resData = ['data' => $data, 'message' => $message, 'status' => $status];
                                            }

                                            $activity = "Withdraw ".$req->currencyCode.''.$req->amount." from Wallet to EXBC Prepaid Card";
                                            $credit = 0;
                                            $debit = $req->amount;
                                            $reference_code = $transaction_id;
                                            $balance = 0;
                                            $trans_date = date('Y-m-d');
                                            $status = "Delivered";
                                            $action = "Wallet debit";
                                            $regards = $thisuser->ref_code;
                                            $statement_route = "wallet";

                                            $walletBal = $thisuser->wallet_balance - $req->amount;
                                                $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                User::where('api_token', $req->bearerToken())->update([
                                                    'wallet_balance' => $walletBal,
                                                    'number_of_withdrawals' => $no_of_withdraw
                                                ]);

                                            // Senders statement
                                            $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                                            $this->createNotification($thisuser->ref_code, "Hello ".strtoupper($thisuser->name).", ".$message);

                                            $this->getfeeTransaction($transaction_id, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);
                                        }
                                        elseif($req->card_type == "Bank Account"){

                                            $bankDetails = AddBank::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();                                            
                                            $transaction_id = "wallet-".date('dmY').time();
                                            // Save Payment for Admin
                                            $insRec = BankWithdrawal::updateOrInsert(['transaction_id' => $transaction_id], ['transaction_id' => $transaction_id, 'ref_code' => $thisuser->ref_code, 'bank_id' => $req->card_id, 'amountToSend' => $req->amounttosend]);


                                            $mydata = BankWithdrawal::where('transaction_id', $transaction_id)->first();


                                            $status = 200;
                                            $data = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();
                                            $message = "Your wallet withdrawal to Bank Account ".$bankDetails->accountNumber." - ".$bankDetails->bankName." has been received. This will take 10 working days to process payment. Thanks";


                                            $walletBal = $thisuser->wallet_balance - $req->amount;
                                                $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                User::where('api_token', $req->bearerToken())->update([
                                                    'wallet_balance' => $walletBal,
                                                    'number_of_withdrawals' => $no_of_withdraw
                                                ]);


                                            $activity = "Withdraw ".$req->currencyCode.''.number_format($req->amount, 2)." from Wallet to Bank Account ".$bankDetails->bankName." - ".$bankDetails->accountNumber;
                                            $credit = 0;
                                            $debit = number_format($req->amount, 2);
                                            $reference_code = $transaction_id;
                                            $balance = 0;
                                            $trans_date = date('Y-m-d');
                                            $thistatus = "Delivered";
                                            $action = "Wallet debit";
                                            $regards = $thisuser->ref_code;
                                            $statement_route = "wallet";

                                            // Senders statement
                                            $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $thistatus, $action, $regards, 1, $statement_route);


                                            $sendMsg = 'Hello '.strtoupper($thisuser->name).', The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your Bank Account '.$bankDetails->bankName.' and Account Number: '.$bankDetails->accountNumber.' has been received and will take up to 10 working days to process payment. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                                                $sendPhone = "+".$thisuser->code.$thisuser->telephone;

                                            $this->createNotification($thisuser->ref_code, $sendMsg);

                                            $this->getfeeTransaction($transaction_id, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);


                                            $resData = ['data' => $data, 'message' => $message, 'status' => $status];


                                        }
                                        else{

                                            if(isset($getTrans) == true){
                                                $transaction_id = $getTrans->reference_code;
                                            }
                                            else{
                                                $transaction_id = "wallet-".date('dmY').time();
                                            }

                                            $customer_id = $thisuser->ref_code;

                                            // Get Card Detail
                                            $card_number = $cardDetails->card_number;
                                            $month = $cardDetails->month;
                                            $year = $cardDetails->year;


                                            $this->creditCardWithdrawalRequest($thisuser->ref_code, $transaction_id, $customer_id, $card_number, $month, $year, $req->amount);


                                            // Proceed to Withdrawal

                                            // $response = $this->monerisWalletProcess($req->bearerToken(), $req->card_id, $monerisDeductamount, "ind_refund", "PaySprint Withdraw from Wallet to ".$thisuser->name, $req->mode);


                                            // if($response->responseData['Message'] == "APPROVED           *                    ="){

                                            $walletBal = $thisuser->wallet_balance - $req->amount;
                                                $no_of_withdraw = $thisuser->number_of_withdrawals + 1;

                                                User::where('api_token', $req->bearerToken())->update([
                                                    'wallet_balance' => $walletBal,
                                                    'number_of_withdrawals' => $no_of_withdraw
                                                ]);

                                                // Update Statement

                                                $userData = User::select('id', 'ref_code as refCode', 'name', 'email', 'telephone', 'wallet_balance as walletBalance', 'number_of_withdrawals as noOfWithdrawals')->where('api_token', $req->bearerToken())->first();

                                                $activity = "Withdraw ".$req->currencyCode.''.number_format($req->amount, 2)." from Wallet to Credit/Debit card";
                                                $credit = 0;
                                                $debit = number_format($req->amount, 2);
                                                // $reference_code = $response->responseData['ReceiptId'];
                                                $reference_code = $transaction_id;
                                                $balance = 0;
                                                $trans_date = date('Y-m-d');
                                                $status = "Delivered";
                                                $action = "Wallet debit";
                                                $regards = $thisuser->ref_code;
                                                $statement_route = "wallet";

                                                // Senders statement
                                                $this->insStatement($thisuser->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);

                                                $this->getfeeTransaction($reference_code, $thisuser->ref_code, $req->amount, $req->commissiondeduct, $req->amounttosend);


                                                // Notification

                                                $cardDetails = AddCard::where('id', $req->card_id)->where('user_id', $thisuser->id)->first();

                                                $cardNo = str_repeat("*", strlen($cardDetails->card_number)-4) . substr($cardDetails->card_number, -4);

                                                $this->name = $thisuser->name;
                                                $this->email = $thisuser->email;
                                                $this->subject = $req->currencyCode.' '.number_format($req->amount, 2)." has been Withdrawn from your Wallet with PaySprint";

                                                $this->message = '<p>The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your Card Name: <strong>'.$cardDetails->card_name.'</strong> and Number: <strong>'.wordwrap($cardNo, 4, '-', true).'</strong> is successful. This will take about 10 working days before it reflect in your bank account or credit card. </p><p>You now have <strong>'.$req->currencyCode.' '.number_format($walletBal, 2).'</strong> balance in your account</p>';

                                                $sendMsg = 'The withdrawal of '.$req->currencyCode.' '.number_format($req->amount, 2).' to your '.$cardDetails->card_name.' and Number: '.wordwrap($cardNo, 4, '-', true).' is successful. This will take about 10 working days before it reflect in your bank account or credit card. You now have '.$req->currencyCode.' '.number_format($walletBal, 2).' balance in your account';
                                                $sendPhone = "+".$thisuser->code.$thisuser->telephone;


                                                $this->createNotification($thisuser->ref_code, $sendMsg);


                                                $this->sendMessage($sendMsg, $sendPhone);

                                                $this->sendEmail($this->email, "Fund remittance");


                                                $userInfo = User::select('id', 'code as countryCode', 'ref_code as refCode', 'name', 'email', 'password', 'address', 'telephone', 'city', 'state', 'country', 'zip as zipCode', 'avatar', 'api_token as apiToken', 'approval', 'accountType', 'wallet_balance as walletBalance', 'number_of_withdrawals as numberOfWithdrawal', 'transaction_pin as transactionPin', 'currencyCode', 'currencySymbol')->where('api_token', $req->bearerToken())->first();

                                                $data = $userInfo;
                                                $status = 200;
                                                $message = $sendMsg;
                                                // $message = $req->currencyCode.' '.number_format($req->amount, 2).' is debited from your Wallet';

                                            // }
                                            // else{
                                            //     $data = [];
                                            //         $message = $response->responseData['Message'];
                                            //         $status = 400;
                                            // }

                                        }

                                            
                                        

                                        }

                                    }
                                    else{
                                        $data = [];
                                        $message = "Invalid login password";
                                        $status = 400;
                                    }

                                }

                    }
                    
                }
            
            else{

                $error = implode(",",$validator->messages()->all());

                $data = [];
                $status = 400;
                $message = $error;
            }




        $resData = ['data' => $data, 'message' => $message, 'status' => $status];


        return $this->returnJSON($resData, $status);


    }


    public function creditCardWithdrawalRequest($ref_code, $transaction_id, $customer_id, $card_number, $month, $year, $amount){

        $query = ['ref_code' => $ref_code, 'transaction_id' => $transaction_id, 'customer_id' => $customer_id, 'card_number' => $card_number, 'month' => $month, 'year' => $year, 'amount' => $amount, 'status' => 'PENDING'];

        CcWithdrawal::insert($query);

    }


        public function debitWalletForCard($ref_code, $amount, $purpose, $transaction_id){


            $myWallet = User::where('ref_code', $ref_code)->first();

            // Deduct $20 for EXBC Card
            $wallet_balance = $myWallet->wallet_balance - $amount;

            // Update walllet balance
            User::where('ref_code', $ref_code)->update(['wallet_balance' => $wallet_balance]);


            $data = User::where('ref_code', $ref_code)->first();

            $status = 200;

            $resData = ['data' => $data,'message' => 'success', 'status' => $status];

            // Send SMS
            $sendMsg = "Hi ".$data->name.", ".$data->currencyCode." ".number_format($amount, 2)." was deducted from your PaySprint wallet for ".$purpose." load request. Your new wallet balance is ".$data->currencyCode.' '.number_format($wallet_balance, 2).". If you did not make this transfer, kindly login to your PaySprint Account to change your Transaction PIN and report the issue to PaySprint Admin using Contact Us.";

            $sendPhone = "+".$data->code.$data->telephone;

            $this->sendMessage($sendMsg, $sendPhone);

            $this->createNotification($ref_code, $sendMsg);

            // Wallet Statement

            // Insert Statement
            $activity = "Debited ".$data->currencyCode." ".number_format($amount, 2)." for ".$purpose." load request from PaySprint Wallet.";
            $credit = 0;
            $debit = number_format($amount, 2);
            $reference_code = $transaction_id;
            $balance = 0;
            $trans_date = date('Y-m-d');
            $status = "Delivered";
            $action = "Wallet debit";
            $regards = $ref_code;

            $statement_route = "wallet";

            // Senders statement
            $this->insStatement($data->email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);


        return $resData;
    }





    public function monerisWalletProcess($bearer, $card_id, $dollaramount, $type, $description, $mode){

        if(env('APP_ENV') == 'local'){
            $mode = "test";
        }
        else{
            $mode = "live";
        }



        if($mode == "test"){
            if($type == "purchase"){
                // Test API
                $store_id='monca04155';
                $api_token='KvTMr066FKlJm9rD3i71';
            }
            else{
                // Test API
                $store_id='store5';
                $api_token='yesguy';
            }

            $setMode = true;
        }
        else{
            // Live API
            $store_id='gwca045238';
            $api_token='V9XOY4JBS4JII01xBFch';

            $setMode = false;
        }

        


        $thisuser = User::where('api_token', $bearer)->first();

        // Get Card Details
        $cardDetails = AddCard::where('id', $card_id)->where('user_id', $thisuser->id)->first();


        $type=$type;
        $cust_id= $thisuser->ref_code;
        $order_id='ord-'.date("dmy-Gis");
        // $amount= number_format($dollaramount, 2);
        $amount= $dollaramount;

        if($thisuser->country == "Canada"){
            $amount= number_format($dollaramount, 2);
        }
        else{
            $amount= $dollaramount;
        }

        

        $month = $cardDetails->month;

        $pan= $cardDetails->card_number;
        $expiry_date= $cardDetails->year.$month;
        $crypt='7';
        $dynamic_descriptor= $description;
        $status_check = 'false';

        /*********************** Transactional Associative Array **********************/
        $txnArray=array('type'=>$type,
                'order_id'=>$order_id,
                'cust_id'=>$cust_id,
                'amount'=>$amount,
                'pan'=>$pan,
                'expdate'=>$expiry_date,
                'crypt_type'=>$crypt,
                'dynamic_descriptor'=>$dynamic_descriptor
            );

        // dd($txnArray);
        /**************************** Transaction Object *****************************/
        $mpgTxn = new mpgTransaction($txnArray);


        /******************* Credential on File **********************************/
        $cof = new CofInfo();
        $cof->setPaymentIndicator("Z");
        $cof->setPaymentInformation("2");
        $cof->setIssuerId("168451306048014");
        $mpgTxn->setCofInfo($cof);

        /****************************** Request Object *******************************/
        $mpgRequest = new mpgRequest($mpgTxn);
        $mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
        $mpgRequest->setTestMode($setMode); //false or comment out this line for production transactions
        /***************************** HTTPS Post Object *****************************/
        /* Status Check Example
        $mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);
        */
        $mpgHttpPost = new mpgHttpsPost($store_id,$api_token,$mpgRequest);
        /******************************* Response ************************************/
        $mpgResponse=$mpgHttpPost->getMpgResponse();

        return $mpgResponse;
    }



public function orgPaymentInvoice(Request $req){


		/**************************** Request Variables *******************************/

/************************* Transactional Variables ****************************/

// Test API
// $store_id='monca04155';
// $api_token='KvTMr066FKlJm9rD3i71';

// Live API
$store_id='gwca045238';
$api_token='V9XOY4JBS4JII01xBFch';

// $type='purchase';
// $cust_id='cust id';
// $order_id='ord-'.date("dmy-Gis");
// $amount='1.00';
// $pan='4242424242424242';
// $expiry_date='2011';
// $crypt='7';
// $dynamic_descriptor='123';
// $status_check = 'false';

$type='purchase';
$cust_id= $req->user_id;
$order_id='ord-'.date("dmy-Gis");


if($req->commission == "on"){
    $amount= number_format($req->amount, 2);
    $approve_commission = "Yes";
}
else{

    $amount= number_format($req->amount+$req->commissiondeduct, 2);
    $approve_commission = "No";

}




$month = $req->month;

$pan= $req->creditcard_no;
$expiry_date= $req->expirydate.$month;
$crypt='7';
$dynamic_descriptor= 'PaySprint Send Money';
$status_check = 'false';


/*********************** Transactional Associative Array **********************/
$txnArray=array('type'=>$type,
     		    'order_id'=>$order_id,
     		    'cust_id'=>$cust_id,
    		    'amount'=>$amount,
   			    'pan'=>$pan,
   			    'expdate'=>$expiry_date,
   			    'crypt_type'=>$crypt,
   			    'dynamic_descriptor'=>$dynamic_descriptor
				//,'wallet_indicator' => '' //Refer to documentation for details
				//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
   		       );

// dd($txnArray);
/**************************** Transaction Object *****************************/
$mpgTxn = new mpgTransaction($txnArray);


/******************* Credential on File **********************************/
$cof = new CofInfo();
$cof->setPaymentIndicator("Z");
$cof->setPaymentInformation("2");
$cof->setIssuerId("168451306048014");
$mpgTxn->setCofInfo($cof);

/****************************** Request Object *******************************/
$mpgRequest = new mpgRequest($mpgTxn);
$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
$mpgRequest->setTestMode(false); //false or comment out this line for production transactions
/***************************** HTTPS Post Object *****************************/
/* Status Check Example
$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);
*/
$mpgHttpPost = new mpgHttpsPost($store_id,$api_token,$mpgRequest);
/******************************* Response ************************************/
$mpgResponse=$mpgHttpPost->getMpgResponse();

// dd($mpgResponse);



if($mpgResponse->responseData['Message'] == "APPROVED           *                    ="){


    // Get User Info
    $user = User::where('email', $req->orgpayemail)->first();
    

    

    if(isset($user)){
        
        // $client = ClientInfo::where('user_id', $req->user_id)->get();

        $client = User::where('ref_code', $req->user_id)->first();


        // Getting the payer
        $userID = $user->email;
        $payerID = $user->ref_code;

        // $req->user_id is for the receiver::

        // Do Insert
        if($req->service != "Others"){
            $service = $req->service;
        }
        else{
            $service = $req->purpose;
        }

        if($req->payment_method == "Wallet"){
            $wallet_balance = Auth::user()->wallet_balance - $req->amount;
        }
        else{
            $wallet_balance = Auth::user()->wallet_balance;
        }


        $insertPay = OrganizationPay::insert(['transactionid' => $mpgResponse->responseData['ReceiptId'], 'coy_id' => $req->user_id, 'user_id' => $userID, 'purpose' => $service, 'amount' => $req->amount, 'withdraws' => $req->amount, 'state' => 1, 'payer_id' => $payerID, 'amount_to_send' => $req->amounttosend, 'commission' => $req->commissiondeduct, 'approve_commission' => $approve_commission, 'amountindollars' => $req->conversionamount]);

        if($insertPay == true){

            // Update Wallet
            User::where('email', Auth::user()->email)->update(['wallet_balance' => $wallet_balance]);

            // Send mail to both parties

            // $this->to = "bambo@vimfile.com";
            $this->to = $client->email;
            $this->name = $user->name;
            $this->coy_name = $client->name;
            // $this->email = "bambo@vimfile.com";
            $this->email = $user->email;
            $this->amount = $req->amounttosend;
            $this->paypurpose = $service;
            $this->subject = "Payment Received from ".$user->name." for ".$service;
            $this->subject2 = "Your Payment to ".$client->name." was successfull";

            // Mail to receiver
            $this->sendEmail($this->to, "Payment Received");

            // Mail from Sender

            $this->sendEmail($this->email, "Payment Successful");


            // Insert Statement
            $activity = "Payment to ".$client->name." on ".$service;
            $credit = 0;
            $debit = $req->amount + $req->commissiondeduct;
            $reference_code = $mpgResponse->responseData['ReceiptId'];
            $balance = 0;
            $trans_date = date('Y-m-d');
            $status = "Pending";
            $action = "Payment";
            $regards = $req->user_id;
            $statement_route = "invoice";

            // Senders statement
            $this->insStatement($userID, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, 1, $statement_route);
            
            // Receiver Statement
            $this->insStatement($client->email, $reference_code, "Received money for ".$service." from ".$user->name, $req->amount, 0, $balance, $trans_date, $status, "Invoice", $client->ref_code, 1, $statement_route);



            $resData = ['res' => 'Payment Sent Successfully', 'message' => 'success', 'title' => 'Good!'];

            $response = 'Payment Sent Successfully';
            $action = 'success';

            return redirect()->route('payorganization')->with($action, $response);

        }
        else{
            $resData = ['res' => 'Something went wrong', 'message' => 'info', 'title' => 'Oops!'];

            $response = 'Something went wrong';
            $action = 'error';

            return redirect()->back()->with($action, $response);
        }
    }
    
    else{
        $resData = ['res' => 'Cannot Process Payment', 'message' => 'error', 'title' => 'Oops!'];

        $response = 'Cannot Process Payment';
        $action = 'error';

        return redirect()->back()->with($action, $response);
    }


}
else{
    $resData = ['res' => $mpgResponse->responseData['Message'], 'message' => 'error', 'title' => 'Oops!'];
    
    $response = $mpgResponse->responseData['Message'];
    $action = 'error';

    return redirect()->back()->with($action, $response);

}

    // return $this->returnJSON($resData, 200);


}


public function receivemoneyProcess(Request $req){


    // Explode Currency

    // Insert Record
    $data = ReceivePay::updateOrInsert(['pay_id' => $req->pay_id], ['_token' => $req->_token, 'pay_id' => $req->pay_id, 'sender_id' => $req->sender_id, 'receiver_id' => $req->receiver_id, 'payment_method' => $req->payment_method, 'account_number' => $req->account_number, 'accountname' => $req->accountname, 'amount_to_receive' => $req->amount_to_receive, 'bank_name' => $req->bank_name, 'creditcard_no' => $req->creditcard_no, 'currency' => $req->currency, 'purpose' => $req->purpose]);

    // Update WALLET
    $wallet = Auth::user()->wallet + $req->amount_to_receive;

    User::where('email', Auth::user()->email)->update(['wallet_balance' => $wallet]);

    // Update OrganozationPay

    OrganizationPay::where('id', $req->pay_id)->update(['request_receive' => 2]);

    $response = 'Money successfully transferred to your '.$req->payment_method;
    $action = 'success';

    return redirect()->route('payorganization')->with($action, $response);

}







    public function insStatement($email, $reference_code, $activity, $credit, $debit, $balance, $trans_date, $status, $action, $regards, $state, $statement_route){
        Statement::insert(['user_id' => $email, 'reference_code' => $reference_code, 'activity' => $activity, 'credit' => $credit, 'debit' => $debit, 'balance' => $balance, 'trans_date' => $trans_date, 'status' => $status, 'action' => $action, 'regards' => $regards, 'state' => $state, 'statement_route' => $statement_route]);
    }


    // Platform API
    public function doCurl(){
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => $this->url,
            CURLOPT_USERAGENT => 'PaySprint cURL Request',
            CURLOPT_POST => 1,
            CURLOPT_POSTFIELDS => $this->curl_data
        ));

        // Send the request & save response to $resp
        $resp = curl_exec($curl);

        // Close request to clear up some resources
        curl_close($curl);

        // dd($resp);
        // dd($this->url);
        // dd($this->curl_data);
        return json_decode($resp);

        // exit();
    }


    public function sendEmail($objDemoa, $purpose){
      $objDemo = new \stdClass();
      $objDemo->purpose = $purpose;
        if($purpose == "Payment Received"){

            $objDemo->name = $this->name;
            $objDemo->email = $this->email;
            $objDemo->amount = $this->amount;
            $objDemo->paypurpose = $this->paypurpose;
            $objDemo->coy_name = $this->coy_name;
            $objDemo->subject = $this->subject;

        }
        elseif($purpose == "Payment Successful"){

            $objDemo->name = $this->name;
            $objDemo->email = $this->email;
            $objDemo->amount = $this->amount;
            $objDemo->paypurpose = $this->paypurpose;
            $objDemo->coy_name = $this->coy_name;
            $objDemo->subject = $this->subject2;

        }

        elseif($purpose == 'Fund remittance'){
            $objDemo->name = $this->name;
            $objDemo->email = $this->email;
            $objDemo->subject = $this->subject;
            $objDemo->message = $this->message;
        }

      Mail::to($objDemoa)
            ->send(new sendEmail($objDemo));
   }

}

